---
apiVersion: v2
appVersion: 1.26.0
description: Vaultwarden is a Bitwarden compatable server in Rust
name: vaultwarden
version: 5.3.3
kubeVersion: ">=1.16.0-0"
keywords:
  - Vaultwarden
  - bitwardenrs
home: "https://github.com/k8s-at-home/charts/tree/master/charts/stable/vaultwarden"
icon: "https://sesoodan.sirv.com/bitwarden_rs.png"
sources:
  - https://github.com/dani-garcia/vaultwarden
maintainers:
  - name: Compunctus
    email: iaroslav@dronskii.ru
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.0
  - name: mariadb
    version: 11.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 12.1.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
