---
apiVersion: v2
appVersion: 1.29.0
description: Vaultwarden is a Bitwarden compatable server in Rust
name: vaultwarden
version: 5.3.9
kubeVersion: ">=1.16.0-0"
keywords:
  - Vaultwarden
  - bitwardenrs
home: "https://github.com/k8s-at-home/charts/tree/master/charts/stable/vaultwarden"
icon: "https://upload.wikimedia.org/wikipedia/commons/5/55/Bitwarden_Logo_2018.png"
sources:
  - https://github.com/dani-garcia/vaultwarden
maintainers:
  - name: Compunctus
    email: iaroslav@dronskii.ru
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: mariadb
    version: 11.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: switch back to common chart from k8s-home
